-- Script untuk mengubah kolom timestamp agar menggunakan CURRENT_TIMESTAMP dengan timezone yang benar
-- PENTING: Backup database Anda sebelum menjalankan script ini!

USE db_reportify;

-- Set timezone
SET time_zone = '+07:00';

-- Ubah kolom created_at dan updated_at di semua tabel
-- Ini akan membuat MySQL secara otomatis menggunakan waktu lokal (+07:00)

-- Table: users
ALTER TABLE users 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: levels
ALTER TABLE levels 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: majors
ALTER TABLE majors 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: rombels
ALTER TABLE rombels 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: rooms
ALTER TABLE rooms 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: classes
ALTER TABLE classes 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: students
ALTER TABLE students 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: subjects
ALTER TABLE subjects 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: teaching_assignments
ALTER TABLE teaching_assignments 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: schedules
ALTER TABLE schedules 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: attendances
ALTER TABLE attendances 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: assignments
ALTER TABLE assignments 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: announcements
ALTER TABLE announcements 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Table: student_assignments
ALTER TABLE student_assignments 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Verifikasi perubahan
SHOW CREATE TABLE levels;

SELECT 'Fix applied successfully!' as status;
